name: 'Lint and Auto-Fix Code'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint & Auto-Fix Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python Linters & Formatters
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Run Auto-Fix for Python
        run: |
          black . 
          isort .

      - name: Run Linter for Python
        run: flake8 .

      - name: Commit Python Fixes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git diff --cached --quiet || git commit -m "Auto-fixed Python formatting issues"
          git push origin HEAD:${{ github.ref }} || echo "No changes to commit"

  lint_js:
    name: Lint & Auto-Fix JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install JavaScript Linters & Formatters
        run: |
          npm install eslint prettier eslint-config-prettier eslint-plugin-prettier --save-dev

      - name: Run Auto-Fix for JavaScript
        run: npx eslint . --fix

      - name: Commit JavaScript Fixes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git diff --cached --quiet || git commit -m "Auto-fixed JavaScript formatting issues"
          git push origin HEAD:${{ github.ref }} || echo "No changes to commit"
