name: 'Lint and Fix Code'
on:
  push:
    branches: [master, main, test]
  pull_request:
    branches: [master, main, test]

jobs:
  lint_python:
    name: Auto-Fix Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort

      - name: Auto-Fix Python Issues
        run: |
          black .
          isort .
          flake8 . --exit-zero

      - name: Commit Fixes (if any)
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Auto-fix Python linting" || echo "No changes to commit"
          git push

  lint_js:
    name: Auto-Fix JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install ESLint & Prettier
        run: npm install --save-dev eslint prettier

      - name: Auto-Fix JavaScript Issues
        run: |
          npx eslint . --fix
          npx prettier --write .

      - name: Commit Fixes (if any)
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Auto-fix JavaScript linting" || echo "No changes to commit"
          git push
