name: Auto Fix and PR

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  autofix:
    name: Auto-Fix Code and Create PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Python & JS linters and formatters
        run: |
          python -m pip install --upgrade pip
          pip install autopep8 flake8
          npm install -g jshint prettier

      - name: Auto-fix Python files
        run: |
          find . -name "*.py" -exec autopep8 --in-place --aggressive --aggressive {} +

      - name: Auto-fix JavaScript files with Prettier
        run: |
          prettier --write "**/*.js"

      - name: Commit and push fixes to new branch
        run: |
          BRANCH_NAME=auto-fix-$(date +%s)

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "Auto-fix: Python/JS lint issues (Prettier + autopep8)"
          git push origin $BRANCH_NAME

          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
